name: Push builds

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-web:
    uses: Srynetix/godot-github-workflows/.github/workflows/build-game-3.5.1.yml@main
    with:
      platform: HTML5
      name: minigolf-3d-sample
      output_name: index.html